<a href="https://colab.research.google.com/github/Data-Science-and-Data-Analytics-Courses/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019/blob/master/homeworks/Homework4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 4

---



## Setup

In [0]:
import sys
from pathlib import Path
from google.colab import drive

# Notebook Library
url = "https://github.com/Data-Science-and-Data-Analytics-Courses/Notebook-Library"
repo = Path("/nblib")
!git clone "{url}" "{repo}"
if repo.parent.as_posix() not in sys.path:
  sys.path.append(repo.parent.as_posix())
%run "{repo}/.Importable.ipynb"

from nblib.imports.Basic import *
from nblib import Git

# Remote
URL = "https://github.com/Data-Science-and-Data-Analytics-Courses/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019"
REPO = Git.clone(URL, dest="/content")
if REPO.as_posix() not in sys.path:
  sys.path.append(REPO.as_posix())

# Working directory
os.chdir(REPO)

from nblib.imports.DS import *
from setup.Setup import *
from nblib import File

clear_output()

Cloning into '/nblib'...
remote: Enumerating objects: 32, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 32 (delta 15), reused 7 (delta 2), pack-reused 0
Unpacking objects: 100% (32/32), done.


importing Jupyter notebook from /nblib/Git.ipynb
Cloning into '/content/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 434 (delta 44), reused 13 (delta 5), pack-reused 340
Receiving objects: 100% (434/434), 5.50 MiB | 8.16 MiB/s, done.
Resolving deltas: 100% (236/236), done.
importing Jupyter notebook from /content/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019/setup/Setup.ipynb


##  Neural Networks
In this problem we will analyze a simple neural network to understand its classification properties. Consider the neural network given in the figure below, with ReLU activation functions (denoted by  f ) on all neurons, and a softmax activation function in the output layer:  
Given an input  x=[x1,x2]T , the hidden units in the network are activated in stages as described by the following equations:  
z1 	=x1W11+x2W21+W01	f(z1)	=max{z1,0}	 	 
 	z2	=x1W12+x2W22+W02	f(z2)	=max{z2,0}	 	 
 	z3	=x1W13+x2W23+W03	f(z3)	=max{z3,0}	 	 
 	z4	=x1W14+x2W24+W04	f(z4)	=max{z4,0}	 
u1 	=f(z1)V11+f(z2)V21+f(z3)V31+f(z4)V41+V01	f(u1)	=max{u1,0}	 	 
 	u2	=f(z1)V12+f(z2)V22+f(z3)V32+f(z4)V42+V02	f(u2)	=max{u2,0}.	 
The final output of the network is obtained by applying the softmax function to the last hidden layer,

$$
o1 \displaystyle = \frac{e^{f(u_1)}}{e^{f(u_1)} +e^{f(u_2)}} \\
o2 \displaystyle = \frac{e^{f(u_1)}}{e^{f(u_1)} +e^{f(u_2)}}
$$o2 	 =ef(u2)ef(u1)+ef(u2). 	 
In this problem, we will consider the following setting of parameters:  
$$
\left[ \begin{array}{ccc} W_{11} &  W_{21} &  W_{01} \\ W_{12} &  W_{22} &  W_{02} \\ W_{13} &  W_{23} &  W_{03} \\ W_{14} &  W_{24} &  W_{04} \\ \end{array}\right] = \left[\begin{array}{ccc} 1 &  0 &  -1 \\ 0 &  1 &  -1 \\ -1 &  0 &  -1 \\ 0 &  -1 &  -1 \end{array}\right],
$$
$$
\left[ \begin{array}{ccccc} V_{11} &  V_{21} &  V_{31} &  V_{41} &  V_{01} \\ V_{12} &  V_{22} &  V_{32} &  V_{42} &  V_{02} \end{array} \right] = \left[ \begin{array}{ccccc} 1 &  1 &  1 &  1 &  0 \\ -1 &  -1 &  -1 &  -1&  2 \end{array}\right].
$$



Compute  X , the matrix of predicted rankings  UVT  given the initial values for  U  and  V .  


In [0]:
u = np.array([6,0,3,6])
v = np.array([4,2,1])
x = np.outer(u, v)
print(x)

[[24 12  6]
 [ 0  0  0]
 [12  6  3]
 [24 12  6]]


Compute the squared error term, and the regularization terms in for the current estimate  X .  


In [0]:
la = 1 # lambda
y = ma.masked_invalid([[5, np.nan, 7],
                      [np.nan, 2, np.nan],
                      [4, np.nan, np.nan],
                      [np.nan, 3, 6]])
err_sq = 1/2 * np.sum((y-x)**2)
reg = 1/2 * la * (np.sum(u**2) + np.sum(v**2))
print(err_sq)
print(reg)

255.5
51.0


Suppose  V  is kept fixed. Run one step of the algorithm to find the new estimate  U(1) .

Enter the  U(1)  as a list of numbers,  [U(1)1,U(1)2,U(1)3,U(1)4] :  


In [0]:
U = sym.Matrix(sym.symarray('U', (1, 4)))
V = sym.Matrix(sym.symarray('V', (1, 3)))
Y = sym.Matrix(sym.symarray('Y', (4, 3)))
Known = sym.Matrix([[1, np.nan, 1],
                    [np.nan, 1, np.nan],
                    [1, np.nan, np.nan],
                    [np.nan, 1, 1]])
Y = matrix_multiply_elementwise(Y,Known)

X = U.T * V
Z = Y - X
Z = sym.simplify(1/2 * matrix_multiply_elementwise(Z,Z)) # squared error component matrix
sym.pprint(Z)

RegU = 1/2 * sym.Symbol("lamda") * matrix_multiply_elementwise(U, U) # regularization of U
sym.pprint(RegU)

RegV = 1/2 * sym.Symbol("lamda") * matrix_multiply_elementwise(V, V) # regularization of V
sym.pprint(RegV)

⎡                      2                                                 2⎤
⎢0.5⋅(U₀ ₀⋅V₀ ₀ - Y₀ ₀)             nan            0.5⋅(U₀ ₀⋅V₀ ₂ - Y₀ ₂) ⎥
⎢                                                                         ⎥
⎢                                               2                         ⎥
⎢          nan            0.5⋅(U₀ ₁⋅V₀ ₁ - Y₁ ₁)             nan          ⎥
⎢                                                                         ⎥
⎢                      2                                                  ⎥
⎢0.5⋅(U₀ ₂⋅V₀ ₀ - Y₂ ₀)             nan                      nan          ⎥
⎢                                                                         ⎥
⎢                                               2                        2⎥
⎣          nan            0.5⋅(U₀ ₃⋅V₀ ₁ - Y₃ ₁)   0.5⋅(U₀ ₃⋅V₀ ₂ - Y₃ ₂) ⎦
⎡        2            2            2            2  ⎤
⎣0.5⋅U₀ ₀ ⋅λ  0.5⋅U₀ ₁ ⋅λ  0.5⋅U₀ ₂ ⋅λ  0.5⋅U₀ ₃ ⋅λ⎦
⎡        2            2            2  ⎤
⎣0.5⋅V₀ ₀ ⋅λ  0.5⋅

In [0]:
subs = {"V_0_0": v[0], "V_0_1": v[1], "V_0_2": v[2],
        "Y_0_0": y[0, 0], "Y_0_2": y[0, 2],
        "Y_1_1": y[1, 1],
        "Y_2_0": y[2, 0],
        "Y_3_1": y[3, 1], "Y_3_2": y[3, 2],
        "lamda": la}
# U(1)
i = sym.Symbol("i")
j = sym.Symbol("j")
for k in range(4):
  difZ = Z.diff(U[0, k])
  err_sq = sym.Sum(difZ[i, j], (i, 0, 3), (j, 0, 2)).doit()
  sym.pprint(err_sq)

  difRegU = RegU.diff(U[0, k])
  reg = sym.Sum(difRegU[i, j], (i, 0, 0), (j, 0, 3)).doit()
  sym.pprint(reg)

  sym.pprint(sym.solve(err_sq+reg, U[0,k]))
  print(sym.solve(err_sq+reg, U[0,k])[0].subs(subs).evalf())

1.0⋅V₀ ₀⋅(U₀ ₀⋅V₀ ₀ - Y₀ ₀) + 1.0⋅V₀ ₂⋅(U₀ ₀⋅V₀ ₂ - Y₀ ₂)
1.0⋅U₀ ₀⋅λ
⎡V₀ ₀⋅Y₀ ₀ + V₀ ₂⋅Y₀ ₂⎤
⎢─────────────────────⎥
⎢      2       2      ⎥
⎣  V₀ ₀  + V₀ ₂  + λ  ⎦
1.50000000000000
1.0⋅V₀ ₁⋅(U₀ ₁⋅V₀ ₁ - Y₁ ₁)
1.0⋅U₀ ₁⋅λ
⎡V₀ ₁⋅Y₁ ₁⎤
⎢─────────⎥
⎢    2    ⎥
⎣V₀ ₁  + λ⎦
0.800000000000000
1.0⋅V₀ ₀⋅(U₀ ₂⋅V₀ ₀ - Y₂ ₀)
1.0⋅U₀ ₂⋅λ
⎡V₀ ₀⋅Y₂ ₀⎤
⎢─────────⎥
⎢    2    ⎥
⎣V₀ ₀  + λ⎦
0.941176470588235
1.0⋅V₀ ₁⋅(U₀ ₃⋅V₀ ₁ - Y₃ ₁) + 1.0⋅V₀ ₂⋅(U₀ ₃⋅V₀ ₂ - Y₃ ₂)
1.0⋅U₀ ₃⋅λ
⎡V₀ ₁⋅Y₃ ₁ + V₀ ₂⋅Y₃ ₂⎤
⎢─────────────────────⎥
⎢      2       2      ⎥
⎣  V₀ ₁  + V₀ ₂  + λ  ⎦
2.00000000000000


## Feature Vectors Transformation
Consider a sequence of  n -dimensional data points,  x(1),x(2),... , and a sequence of  m -dimensional feature vectors,  z(1),z(2),... , extracted from the  x 's by a linear transformation,  z(i)=Ax(i) . If  m  is much smaller than  n , you might expect that it would be easier to learn in the lower dimensional feature space than in the original data space.  

Suppose  n=6 ,  m=2 ,  z1  is the average of the elements of  x , and  z2  is the average of the first three elements of  x  minus the average of fourth through sixth elements of  x . Determine  A .

Note: Enter  A  in a list format:  [[A11,...,A16],[A21,...,A26]]  


In [0]:
X = sym.Matrix(sym.symarray('X', (1, 6)))
Z = sym.Matrix(sym.symarray('Z', (1, 2)))
A = sym.Matrix(sym.symarray('A', (2, 6)))
Z[0, 0] = sym.Rational(1, 6) * sym.Sum(X[0,j], (j, 0, 5)).doit()
Z[0, 1] = sym.Rational(1, 3) * sym.Sum(X[0,j], (j, 0, 2)).doit() - sym.Rational(1, 3) * sym.Sum(X[0,j], (j, 3, 5)).doit()
sym.pprint(X)
sym.pprint(Z)
sym.pprint(A)
print("Match A*X.T and Z.T")
sym.pprint(A*X.T)
sym.pprint(Z.T)

print("A")
sym.Matrix([[1/6, 1/6, 1/6, 1/6, 1/6, 1/6],
            [1/3, 1/3, 1/3, -1/3, -1/3, -1/3]])

[X₀ ₀  X₀ ₁  X₀ ₂  X₀ ₃  X₀ ₄  X₀ ₅]
⎡X₀ ₀   X₀ ₁   X₀ ₂   X₀ ₃   X₀ ₄   X₀ ₅  X₀ ₀   X₀ ₁   X₀ ₂   X₀ ₃   X₀ ₄   X
⎢──── + ──── + ──── + ──── + ──── + ────  ──── + ──── + ──── - ──── - ──── - ─
⎣ 6      6      6      6      6      6     3      3      3      3      3      

₀ ₅⎤
───⎥
3  ⎦
⎡A₀ ₀  A₀ ₁  A₀ ₂  A₀ ₃  A₀ ₄  A₀ ₅⎤
⎢                                  ⎥
⎣A₁ ₀  A₁ ₁  A₁ ₂  A₁ ₃  A₁ ₄  A₁ ₅⎦
Match A*X.T and Z.T
⎡A₀ ₀⋅X₀ ₀ + A₀ ₁⋅X₀ ₁ + A₀ ₂⋅X₀ ₂ + A₀ ₃⋅X₀ ₃ + A₀ ₄⋅X₀ ₄ + A₀ ₅⋅X₀ ₅⎤
⎢                                                                     ⎥
⎣A₁ ₀⋅X₀ ₀ + A₁ ₁⋅X₀ ₁ + A₁ ₂⋅X₀ ₂ + A₁ ₃⋅X₀ ₃ + A₁ ₄⋅X₀ ₄ + A₁ ₅⋅X₀ ₅⎦
⎡X₀ ₀   X₀ ₁   X₀ ₂   X₀ ₃   X₀ ₄   X₀ ₅⎤
⎢──── + ──── + ──── + ──── + ──── + ────⎥
⎢ 6      6      6      6      6      6  ⎥
⎢                                       ⎥
⎢X₀ ₀   X₀ ₁   X₀ ₂   X₀ ₃   X₀ ₄   X₀ ₅⎥
⎢──── + ──── + ──── - ──── - ──── - ────⎥
⎣ 3      3      3      3      3      3  ⎦
A


Matrix([
[0.166666666666667, 0.166666666666667, 0.166666666666667,  0.166666666666667,  0.166666666666667,  0.166666666666667],
[0.333333333333333, 0.333333333333333, 0.333333333333333, -0.333333333333333, -0.333333333333333, -0.333333333333333]])