<a href="https://colab.research.google.com/github/Data-Science-and-Data-Analytics-Courses/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019/blob/master/exercises/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Networks 

---



## Setup

In [0]:
import sys
from pathlib import Path
from google.colab import drive

# Notebook Library
url = "https://github.com/Data-Science-and-Data-Analytics-Courses/Notebook-Library"
repo = Path("/nblib")
!git clone "{url}" "{repo}"
if repo.parent.as_posix() not in sys.path:
  sys.path.append(repo.parent.as_posix())
%run "{repo}/.Importable.ipynb"

from nblib.imports.Basic import *
from nblib import Git

# Remote
URL = "https://github.com/Data-Science-and-Data-Analytics-Courses/MITx---Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning-Jun-11-2019"
REPO = Git.clone(URL, dest="/content")
if REPO.as_posix() not in sys.path:
  sys.path.append(REPO.as_posix())

# Working directory
os.chdir(REPO)

from nblib.imports.DS import *
from setup.Setup import *

clear_output()

## Hidden Layer Models
For the following set of problems, let's consider a simple 2-dimensional classification task. The training set is made up of  4  points listed below:  

 	 x(1)=(−1,−1) 	 , 	 y(1)=1 	 	 
 	 x(2)=(1,−1) 	 , 	 y(2)=−1 	 	 
 	 x(3)=(−1,1) 	 , 	 y(3)=−1 	 	 
 	 x(4)=(1,1) 	 , 	 y(4)=1 	 	 
The dataset is illustrated below (blue - positive, red - negative)  
For simplicity, assume that we are only interested in binary classification problems for now. That is,  y(i)  can be either  1  or  −1 .  


### Linear Separability After First Layer
For this problem, let us focus on a network with one hidden layer and two units in that layer:  
Let  f(i)1,f(i)2  denote the output of the two units in the hidden layer corresponding to the input  x(i)  respectively, i.e.

 	 f(i)1 	 = 	 f(w01+(w11x(i)1+w21x(i)2)) 	 	 
 	 f(i)2 	 = 	 f(w02+(w12x(i)1+w22x(i)2)) 	 	 
Consider the set  D′={([f(i)1,f(i)2],y(i)),i=1,2,3,4} .

Assume that f is the linear activation function given by  f(z)=2z−3 .

For which of the following values of weights would the set  D′  be linearly separable? (Select all that apply.)  
 w11=w21=0,w12=w22=0,w01=w02=0   
 w11=w21=2,w12=w22=−2,w01=w02=1   
 w11=w21=−2,w12=w22=2,w01=w02=1  
 

In [4]:
x = np.array([[-1, -1],
              [1, -1],
              [-1, 1],
              [1, 1]])
y = np.array([1, -1, -1, 1])

w = np.array([[0, 0], 
              [0, 0]])
w0 = np.array([0, 0])
f = 2*(x.dot(w) + w0) - 3
print(f)

w = np.array([[2, -2], 
              [2, -2]])
w0 = np.array([1, 1])
f = 2*(x.dot(w) + w0) - 3
print(f)

w = np.array([[-2, 2], 
              [-2, 2]])
w0 = np.array([1, 1])
f = 2*(x.dot(w) + w0) - 3
print(f)

[[-3 -3]
 [-3 -3]
 [-3 -3]
 [-3 -3]]
[[-9  7]
 [-1 -1]
 [-1 -1]
 [ 7 -9]]
[[ 7 -9]
 [-1 -1]
 [-1 -1]
 [-9  7]]


### Non-linear Activation Functions
Again, let's focus on a network with one hidden layer with two units and use the same training set as above. The weights of the network are given as follows:

 	 w11=1,w21=−1,w01=1 	 	 
 	 w12=−1,w22=1,w02=1 	 	 
Let  f1,f2  be the outputs of the first and second unit respectively.

Consider the set  D′={([f(i)1,f(i)2],y(i)),i=1,2,3,4}  
For which of the following functions  f , would the set  D′  be linearly separable? (Select one or more that apply.)


 f(z)=5z−2  
 f(z)=ReLU(z)  
 f(z)=tanh(z)  
 f(z)=z  
 

In [13]:
x = np.array([[-1, -1],
              [1, -1],
              [-1, 1],
              [1, 1]])
y = np.array([1, -1, -1, 1])

w = np.array([[1, -1], 
              [-1, 1]])
w0 = np.array([1, 1])

# 5z−2
f = 5*(x.dot(w) + w0) - 2
print(f)

# ReLU
f = np.maximum([0], (x.dot(w) + w0))
print(f)

# tanh
f = np.tanh(x.dot(w) + w0)
print(f)

# z
f = x.dot(w) + w0
print(f)

[[ 3  3]
 [13 -7]
 [-7 13]
 [ 3  3]]
[[1 1]
 [3 0]
 [0 3]
 [1 1]]
[[ 0.76159416  0.76159416]
 [ 0.99505475 -0.76159416]
 [-0.76159416  0.99505475]
 [ 0.76159416  0.76159416]]
[[ 1  1]
 [ 3 -1]
 [-1  3]
 [ 1  1]]
